replicaCount: 1

image:
  repository: alazar111/socialbook-frontend
  tag: latest
  pullPolicy: Always

rolloutId: "frontend-90d6c3d"

service:
  type: ClusterIP
  port: 80

env:
  VITE_API_BASE: /api
  VITE_KEYCLOAK_URL: https://keycloak.ltu-m7011e-11.se
  VITE_KEYCLOAK_REALM: Userenter
  VITE_KEYCLOAK_CLIENT_ID: socialbook
  FRONTEND_IMAGE_TAG: latest
