replicaCount: 1

image:
  repository: alazar111/socialbook-frontend
  tag: latest
  pullPolicy: Always

rolloutId: "00500778fe2fa3b05c67039187ead4771ca8cb02"

service:
  type: ClusterIP
  port: 80
#dÂ§efined in order to set environment variables in the frontend container



env:
  VITE_API_BASE: /api
  VITE_KEYCLOAK_URL: https://keycloak.ltu-m7011e-11.se
  VITE_KEYCLOAK_REALM: Userenter
  VITE_KEYCLOAK_CLIENT_ID: socialbook
  FRONTEND_IMAGE_TAG: latest
