apiVersion: v1
kind: Secret
metadata:
  name: email-worker-smtp
  namespace: socialbook
type: Opaque
stringData:
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_USER: natanimmayas@gmail.com
  SMTP_PASS: Pajalsta1313
  EMAIL_FROM: natanimmayas@gmail.com
