apiVersion: v2
name: socialbook-stack
description: Umbrella chart to deploy Socialbook frontend + backend with ingress
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: socialbook-backend
    version: 0.1.0
    repository: "file://../socialbook-backend"
    alias: backend
  - name: socialbook-frontend
    version: 0.1.0
    repository: "file://../socialbook-frontend"
    alias: frontend
