apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-mongo-reviews
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-mongo-reviews
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-mongo-users
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-mongo-users
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-mongo-social
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-mongo-social
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-mongo-booklists
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-mongo-booklists
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-mongo-notifications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-mongo-notifications
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-reviews
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=alazar111/socialbook-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-reviews
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-users
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=alazar111/socialbook-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-users
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-social
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=alazar111/socialbook-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-social
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-booklists
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=alazar111/socialbook-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-booklists
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=alazar111/socialbook-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-notifications-worker
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: worker=alazar111/socialbook-notifications-worker
    argocd-image-updater.argoproj.io/worker.update-strategy: latest
    argocd-image-updater.argoproj.io/worker.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/worker.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-notifications-worker
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialbook-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/a-l-a-z-a-r/Socialbook
    targetRevision: Dev
    path: helm/socialbook-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: socialbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
