{{- if .Values.ingress.tlsEnabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "helloworld.clusterIssuerName" . }}
spec:
  acme:
    # Use Let's Encrypt production endpoint.
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ include "helloworld.fullname" . }}-acme-key
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helloworld.fullname" . }}
  annotations:
    {{- if .Values.ingress.tlsEnabled }}
    cert-manager.io/cluster-issuer: {{ include "helloworld.clusterIssuerName" . }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helloworld.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ include "helloworld.fullname" . }}-tls
  {{- end }}
