app:
  name: hello-world
  replicas: 1

domain: helloworld.ltu-m7011e-johan.se
email: johan.kristiansson@ltu.se

message: "Hello from Kubernetes with SSL!"

image:
  repository: hashicorp/http-echo
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 5678

ingress:
  className: nginx
  # Set to false if you want to disable TLS and certificate creation.
  tlsEnabled: true
